Fix potential NullPointerException in close method
Added null check for topFrame before disposing.

20260804-08:29:38.605 Beginning shutdown process
20260804-08:30:21.659 extension budgetgen took a while (43.041 seconds) to respond to event md:file:closing
20260804-08:30:23.858 Exception dispatching event md:file:closing to extension
Error: Cannot invoke "javax.swing.JFrame.dispose()" because "topFrame" is null
java.lang.NullPointerException: Cannot invoke "javax.swing.JFrame.dispose()" because "topFrame" is null
	at com.moneydance.modules.features.mrbutil.MRBReportViewer.close(MRBReportViewer.java:315)
	at com.moneydance.modules.features.budgetreport.BudgetValuesWindow.close(BudgetValuesWindow.java:752)
	at com.moneydance.modules.features.budgetreport.BudgetValuesWindow.goAway(BudgetValuesWindow.java:884)
	at com.moneydance.modules.features.budgetreport.Main.closeConsole(Main.java:158)
	at com.moneydance.modules.features.budgetreport.Main.handleEvent(Main.java:112)
	at com.moneydance.apps.md.controller.Main.sendEventToExtensions(Main.java:1684)
	at com.moneydance.apps.md.controller.AppEventManager.fireEvent(AppEventManager.java:66)
	at com.moneydance.apps.md.controller.Main.setCurrentBook(Main.java:1403)
	at com.moneydance.apps.md.controller.Main.shutdown(Main.java:1481)
	at com.moneydance.apps.md.view.gui.MoneydanceGUI.shutdownApp$lambda$0(MoneydanceGUI.kt:1986)
	at com.moneydance.apps.md.view.gui.TaskIndicator.run(TaskIndicator.java:93)
	at java.base/java.lang.Thread.run(Unknown Source)